version: '3.9'
services:
  app:
    build: .
    container_name: be-starterr
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: yarn dev
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    container_name: be-starter
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_store
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: be-starter-redis
    command: redis-server --requirepass postgres
    ports:
      - '6379:6379'
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
